name: Deploy with Approval

on:
  push:
    branches:
      - master  # Trigger deployment on push to master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy Application
        run: |
          echo "Deploying application..."
          sleep 10  # Simulating deployment process
          echo "Deployment completed successfully."

      - name: Send Slack Notification for Approval
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "🚀 *Deployment Completed for ${{ github.repository }}* \n✅ *Status:* Success\n🔗 *Run Details:* <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Workflow>\n\n⚠️ *Action Required:* Please approve the next step in GitHub Actions."
          }' ${{ secrets.SLACK_WEBHOOK_URL }}

  approval:
    needs: deploy
    runs-on: ubuntu-latest
    environment: production  # Requires manual approval
    steps:
      - name: Approval Received
        run: echo "Manual approval granted. Proceeding with deployment finalization."

      - name: Final Deployment Steps
        run: |
          echo "Executing post-approval deployment steps..."
          sleep 5  # Simulating final process
          echo "Final deployment steps completed."

      - name: Send Slack Notification - Deployment Completed
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "✅ *Deployment successfully finalized for ${{ github.repository }}* \n🔗 *Run Details:* <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Workflow>"
          }' ${{ secrets.SLACK_WEBHOOK_URL }}
