name: Deploy and Notify

on:
  workflow_run:
    workflows: ["Your Deployment Workflow"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Deployment Notification to Slack
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "🚀 Deployment Status: ${{ github.event.workflow_run.conclusion }} for ${{ github.repository }}\n🔗 <${{ github.event.workflow_run.html_url }}|View Workflow Run>"
          }' ${{ secrets.SLACK_WEBHOOK_URL }}
