name: Deploy to Multiple Environments

on:
  push:
    branches:
      - master # Trigger deployment on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: ["Dev", "Test", "Staging", "Prod"] # Define environments for parallel deployment
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up the deployment script
      - name: Prepare deploy.sh
        run: chmod +x deploy.sh # Ensure the script is executable

      # Step 3: Deploy based on the environment
      - name: Deploy to ${{ matrix.environment }}
        run: ./deploy.sh ${{ matrix.environment }} 1.0.0 # Call the script with environment and version
