name: Deploy and Notify with Approval

on:
  push:
    branches:
      - master  # Trigger deployment on push to master

jobs:
  deploy:
    runs-on: ubuntu-latest  # Using GitHub-hosted runner
    strategy:
      matrix:
        environment: ["Dev", "Test", "Staging", "Prod"]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Use latest checkout action

      - name: Prepare deploy.sh
        run: chmod +x deploy.sh

      - name: Deploy to ${{ matrix.environment }}
        run: ./deploy.sh ${{ matrix.environment }} 1.0.0

      - name: Save Final Deployment Script (If Generated)
        uses: actions/upload-artifact@v4  # Update to v4
        with:
          name: finalize-deployment
          path: finalize_deployment.sh

  notify:
    needs: deploy
    runs-on: ubuntu-latest  # GitHub-hosted runner
    steps:
      - name: Send Slack Notification for Approval
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "🚀 *Deployment Completed for ${{ github.repository }}* \n🔍 *Environment:* ${{ matrix.environment }}\n✅ *Status:* Success\n🔗 *Run Details:* <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Workflow>\n\n⚠️ *Action Required:* Please approve the next step in GitHub Actions before proceeding."
          }' ${{ secrets.SLACK_WEBHOOK_URL }}

  approval:
    needs: notify
    runs-on: ubuntu-latest  # GitHub-hosted runner
    environment: production  # Ensures manual approval is required
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Use latest checkout action

      - name: Restore Final Deployment Script (If Generated)
        uses: actions/download-artifact@v4  # Update to v4
        with:
          name: finalize-deployment

      - name: Debug - Verify Script Exists
        run: ls -l finalize_deployment.sh || echo "Script not found"

      - name: Make Script Executable
        run: chmod +x finalize_deployment.sh

      - name: Approval Received
        run: echo "Manual approval granted. Proceeding with deployment finalization."

      - name: Execute Post-Approval Steps
        run: |
          echo "Executing final deployment steps after approval..."
          ./finalize_deployment.sh

      - name: Send Slack Notification - Database Schema Deployed
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "✅ *Database schema is deployed successfully for ${{ github.repository }}* \n\n🎯 *Environment:* ${{ matrix.environment }}\n🔗 *Run Details:* <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Workflow>"
          }' ${{ secrets.SLACK_WEBHOOK_URL }}
